name: Build and Push Docker Image to ACR

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug - List Files
        run: ls -lR /home/sruthi/ems-ops-phase-1

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Log in to ACR
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}

      - name: Set working directory
        run: cd /home/sruthi/ems-ops-phase-1/react-hooks-frontend

      - name: Build Docker Image
        working-directory: /home/sruthi/ems-ops-phase-1/react-hooks-frontend
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/myapp:latest -f Dockerfile .

      - name: Push Docker Image to ACR
        working-directory: /home/sruthi/ems-ops-phase-1/react-hooks-frontend
        run: |
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/myapp:latest

      - name: Log out of Docker
        run: docker logout

