name: Deploy Frontend to Azure Container Apps

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Log in to Azure Container Registry (ACR)
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}

      - name: Build and Push Docker Image (Frontend)
        run: |
          cd react-hooks-frontend
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/my-frontend:latest .
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/my-frontend:latest

      - name: Deploy Frontend to Azure Container Apps
        run: |
          set -e  # Stop script if any command fails

          # Deploy or update the container app
          az containerapp up \
            --name "frontend-app-container" \
            --resource-group "ACR" \
            --environment "managedEnvironment-ACR-9882" \
            --image "applicationimageregistry.azurecr.io/my-frontend:latest" \
            --ingress external \
            --target-port 80 \
            --registry-username "applicationimageregistry" \
            --registry-password "QwDbCRJFaqrmUzx7IV5kbUbFAMAsCW6D/TIzy/QMvf+ACRBFRAuV"
